name: llvm-build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LLVM version to build (eg. 19.1.4)'
        required: true
      build_type:
        description: 'build type'
        type: 'choice'
        options:
          - 'Release'
          - 'Debug'
          - 'RelWithDebInfo'
          - 'MinSizeRel'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: compile llvm and push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker buildx create --use
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --build-arg "VERSION=${{ github.event.inputs.version }}" \
            --build-arg "BUILD_TYPE=${{ github.event.inputs.build_type }}" \
            --tag ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.event.inputs.version }} \
            --push
